spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myshop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    # 地址
    host: 121.37.244.178
    port: 6379
    password: nanling098765
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 10
        max-active: 200
        max-wait: -1ms
  jackson:
    # 设置json时为空不显示
    default-property-inclusion: non_null
    # 设置json的时候给时区+8个小时
    time-zone: GMT+8

server:
  port: 9098
