spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sy1998-+
    url: jdbc:mysql://47.97.192.128:3306/oauth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    # 地址
    host: 47.97.192.128
    port: 6379
    password: sy1998-+
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 10
        max-active: 200
        max-wait: -1ms
  jackson:
    # 设置json时为空不显示
    default-property-inclusion: non_null
    # 设置json的时候给时区+8个小时
    time-zone: GMT+8


server:
  port: 9000

#security:
#  oauth2:
#    client:
#      client-id: entfrm
#      client-secret: entfrm
#      access-token-uri: http://localhost:9000/oauth/token
#      user-authorization-uri: http://localhost:9000/oauth/authorize
#    resource:
#      token-info-uri: http://localhost:9000/oauth/check_token

mybatis:
  type-aliases-package: com.example.oauth2.domain
  mapper-locations: classpath:mapper/**/*.xml
